create table "public"."issues" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "aliases" text[]
);


alter table "public"."issues" enable row level security;

create table "public"."legislators" (
    "id" bigint not null,
    "last_name" text,
    "first_name" text,
    "middle_name" text,
    "suffix" text,
    "nickname" text,
    "full_name" text,
    "birthday" text,
    "gender" text,
    "type" text,
    "state" text,
    "district" text,
    "senate_class" bigint,
    "party" text,
    "url" text,
    "address" text,
    "phone" text,
    "contact_form" text,
    "rss_url" text,
    "twitter" text,
    "twitter_id" bigint,
    "facebook" text,
    "youtube" text,
    "youtube_id" text,
    "mastodon" text,
    "bioguide_id" text,
    "thomas_id" bigint,
    "opensecrets_id" text,
    "lis_id" text,
    "fec_ids" text,
    "cspan_id" bigint,
    "govtrack_id" bigint,
    "votesmart_id" bigint,
    "ballotpedia_id" text,
    "washington_post_id" text,
    "icpsr_id" bigint,
    "wikipedia_id" text
);


alter table "public"."legislators" enable row level security;

-- alter table "public"."officials" alter column "issues" set data type issue[] using "issues"::issue[];

CREATE UNIQUE INDEX issues_pkey ON public.issues USING btree (id);

CREATE UNIQUE INDEX legislators_pkey ON public.legislators USING btree (id);

alter table "public"."issues" add constraint "issues_pkey" PRIMARY KEY using index "issues_pkey";

alter table "public"."legislators" add constraint "legislators_pkey" PRIMARY KEY using index "legislators_pkey";

grant delete on table "public"."issues" to "anon";

grant insert on table "public"."issues" to "anon";

grant references on table "public"."issues" to "anon";

grant select on table "public"."issues" to "anon";

grant trigger on table "public"."issues" to "anon";

grant truncate on table "public"."issues" to "anon";

grant update on table "public"."issues" to "anon";

grant delete on table "public"."issues" to "authenticated";

grant insert on table "public"."issues" to "authenticated";

grant references on table "public"."issues" to "authenticated";

grant select on table "public"."issues" to "authenticated";

grant trigger on table "public"."issues" to "authenticated";

grant truncate on table "public"."issues" to "authenticated";

grant update on table "public"."issues" to "authenticated";

grant delete on table "public"."issues" to "service_role";

grant insert on table "public"."issues" to "service_role";

grant references on table "public"."issues" to "service_role";

grant select on table "public"."issues" to "service_role";

grant trigger on table "public"."issues" to "service_role";

grant truncate on table "public"."issues" to "service_role";

grant update on table "public"."issues" to "service_role";

grant delete on table "public"."legislators" to "anon";

grant insert on table "public"."legislators" to "anon";

grant references on table "public"."legislators" to "anon";

grant select on table "public"."legislators" to "anon";

grant trigger on table "public"."legislators" to "anon";

grant truncate on table "public"."legislators" to "anon";

grant update on table "public"."legislators" to "anon";

grant delete on table "public"."legislators" to "authenticated";

grant insert on table "public"."legislators" to "authenticated";

grant references on table "public"."legislators" to "authenticated";

grant select on table "public"."legislators" to "authenticated";

grant trigger on table "public"."legislators" to "authenticated";

grant truncate on table "public"."legislators" to "authenticated";

grant update on table "public"."legislators" to "authenticated";

grant delete on table "public"."legislators" to "service_role";

grant insert on table "public"."legislators" to "service_role";

grant references on table "public"."legislators" to "service_role";

grant select on table "public"."legislators" to "service_role";

grant trigger on table "public"."legislators" to "service_role";

grant truncate on table "public"."legislators" to "service_role";

grant update on table "public"."legislators" to "service_role";


